from contextlib import redirect_stdout
import io
import shutil
from pydantic import BaseModel
import uuid
from fastapi import File, Request
from fastapi import UploadFile
from starlette.responses import HTMLResponse
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi import WebSocket  # ADD THIS
import os
import pandas as pd
import json
import ml_pipeline
import time
# pyrefly: ignore [missing-import]
import numpy as np
import requests
import re
from typing import List, Optional

app= FastAPI(title="Model Brawl", version="1.0.0")


# 1. Define paths relative to main.py
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Point to the React build folder in the separate directory
REACT_BUILD_DIR = os.path.abspath(os.path.join(BASE_DIR, "..", "Frontend", "dist"))
ASSETS_DIR = os.path.join(REACT_BUILD_DIR, "assets")
UPLOAD_DIR = os.path.join(BASE_DIR, ".uploads")
STATIC_DIR = os.path.join(BASE_DIR, "static")

os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(STATIC_DIR, exist_ok=True)

# 2. Mount static assets (CSS, JS, images) generated by Vite/React
if os.path.exists(ASSETS_DIR):
    app.mount("/assets", StaticFiles(directory=ASSETS_DIR), name="assets")

if os.path.exists(STATIC_DIR):
    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")

tasks: dict = {}

def _read_csv_safe(file_path: str) -> pd.DataFrame:
    """
    Read a CSV with robust encoding fallback and coerce numeric columns.
    Tries utf-8 -> latin-1 -> unicode_escape. After reading, converts any
    string columns that are actually numeric back to numeric types to
    prevent pyarrow large_string errors in sklearn operations.
    """
    df = None
    for enc in ["utf-8", "latin-1", "unicode_escape"]:
        try:
            df = pd.read_csv(file_path, encoding=enc)
            break
        except (UnicodeDecodeError, UnicodeError):
            continue
        except Exception:
            raise

    if df is None:
        raise ValueError("Could not read the CSV with any supported encoding (utf-8, latin-1, unicode_escape).")

    return df


@app.get("/api/health")
async def health_check():
    return {"status": "ok"}

@app.get("/favicon.ico", include_in_schema=False)
async def favicon():
    from fastapi.responses import Response
    return Response(content=b"", media_type="image/x-icon", status_code=204)


HISTORY_DIR = os.path.join(UPLOAD_DIR, ".history")
os.makedirs(HISTORY_DIR, exist_ok=True)

def _get_history_folder(stored_as: str) -> str:
    safe_stored_as = os.path.basename(stored_as)
    folder = os.path.join(HISTORY_DIR, safe_stored_as)
    os.makedirs(folder, exist_ok=True)
    return folder

def _get_history_meta_path(stored_as: str) -> str:
    return os.path.join(_get_history_folder(stored_as), "history.json")

def _load_history_meta(stored_as: str) -> dict:
    meta_path = _get_history_meta_path(stored_as)
    if os.path.exists(meta_path):
        try:
            with open(meta_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return {"steps": [], "current_index": -1}

def _save_history_meta(stored_as: str, meta: dict):
    meta_path = _get_history_meta_path(stored_as)
    # Add last_modified timestamp if not present
    if "last_modified" not in meta:
        meta["last_modified"] = time.time()
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

def _record_dataset_snapshot(stored_as: str, action_desc: str, df: pd.DataFrame,
                             code: str = None, origin: str = "ui", cells: list = None):
    """
    Save a snapshot of the dataset AFTER an action, plus (optionally) the Python
    code that produced it. The code is what lets the Python Notebook rebuild its
    state by replaying every step in order:
        origin="ui"       -> a button in the app (delete column, change dtype...)
        origin="notebook" -> cells the user committed from the notebook
    """
    safe_stored_as = os.path.basename(stored_as)
    folder = _get_history_folder(safe_stored_as)
    meta = _load_history_meta(safe_stored_as)
    current_idx = meta.get("current_index", -1)
    steps = meta.get("steps", [])

    # Truncate forward steps if user performed an action after some undos
    if 0 <= current_idx < len(steps) - 1:
        for s in steps[current_idx + 1:]:
            old_snap = os.path.join(folder, s.get("file", ""))
            if os.path.exists(old_snap):
                try:
                    os.remove(old_snap)
                except Exception:
                    pass
        steps = steps[:current_idx + 1]

    new_step_id = len(steps)
    snap_filename = f"snap_{new_step_id}.csv"
    snap_path = os.path.join(folder, snap_filename)
    df.to_csv(snap_path, index=False)

    steps.append({
        "step_id": new_step_id,
        "file": snap_filename,
        "action": action_desc,
        "timestamp": time.time(),
        "columns": list(df.columns),
        "rows": int(len(df)),
        "origin": origin,
        "code": code,
        "cells": cells,
    })
    meta["steps"] = steps
    meta["current_index"] = len(steps) - 1
    meta["last_modified"] = time.time()  # Always update last_modified
    _save_history_meta(safe_stored_as, meta)

def _undo_dataset_snapshot(stored_as: str) -> tuple:
    safe_stored_as = os.path.basename(stored_as)
    folder = _get_history_folder(safe_stored_as)
    meta = _load_history_meta(safe_stored_as)
    current_idx = meta.get("current_index", -1)
    steps = meta.get("steps", [])

    if current_idx <= 0 or not steps:
        main_file_path = os.path.join(UPLOAD_DIR, safe_stored_as)
        bak_path = main_file_path + ".bak"
        if os.path.exists(bak_path):
            shutil.copy2(bak_path, main_file_path)
            df = _read_csv_safe(main_file_path)
            return df, "Reverted from backup"
        raise ValueError("No actions to undo.")

    undone_action = steps[current_idx]["action"]
    new_idx = current_idx - 1
    target_snap_file = os.path.join(folder, steps[new_idx]["file"])
    if not os.path.exists(target_snap_file):
        raise FileNotFoundError("Snapshot file not found.")

    df = _read_csv_safe(target_snap_file)
    main_file_path = os.path.join(UPLOAD_DIR, safe_stored_as)
    df.to_csv(main_file_path, index=False)

    meta["current_index"] = new_idx
    _save_history_meta(safe_stored_as, meta)
    return df, undone_action

def _redo_dataset_snapshot(stored_as: str) -> tuple:
    safe_stored_as = os.path.basename(stored_as)
    folder = _get_history_folder(safe_stored_as)
    meta = _load_history_meta(safe_stored_as)
    current_idx = meta.get("current_index", -1)
    steps = meta.get("steps", [])

    if current_idx >= len(steps) - 1 or current_idx < 0:
        raise ValueError("No actions to redo.")

    new_idx = current_idx + 1
    target_snap_file = os.path.join(folder, steps[new_idx]["file"])
    if not os.path.exists(target_snap_file):
        raise FileNotFoundError("Snapshot file not found.")

    df = _read_csv_safe(target_snap_file)
    main_file_path = os.path.join(UPLOAD_DIR, safe_stored_as)
    df.to_csv(main_file_path, index=False)

    meta["current_index"] = new_idx
    _save_history_meta(safe_stored_as, meta)
    redone_action = steps[new_idx]["action"]
    return df, redone_action

def _reset_dataset_snapshot(stored_as: str) -> tuple:
    safe_stored_as = os.path.basename(stored_as)
    folder = _get_history_folder(safe_stored_as)
    meta = _load_history_meta(safe_stored_as)
    steps = meta.get("steps", [])

    if not steps:
        raise ValueError("No history available to reset.")

    target_snap_file = os.path.join(folder, steps[0]["file"])
    if not os.path.exists(target_snap_file):
        raise FileNotFoundError("Initial snapshot file not found.")

    df = _read_csv_safe(target_snap_file)
    main_file_path = os.path.join(UPLOAD_DIR, safe_stored_as)
    df.to_csv(main_file_path, index=False)

    _record_dataset_snapshot(safe_stored_as, "Reset dataset to original", df,
                             code="df = _base_df.copy()")
    return df, "Reset dataset to original"

def _build_dataset_response(df: pd.DataFrame, stored_as: str, filename: str = None) -> dict:
    safe_stored_as = os.path.basename(stored_as)
    if filename is None:
        filename = safe_stored_as.split("_", 1)[1] if "_" in safe_stored_as else safe_stored_as

    target_col = df.columns[-1] if len(df.columns) > 0 else ""
    col_info = []
    for col in df.columns:
        col_info.append({
            "name": col,
            "dtype": str(df[col].dtype),
            "null_count": int(df[col].isna().sum()),
            "unique_count": int(df[col].nunique())
        })

    preview_rows = json.loads(df.head(5).to_json(orient="records"))
    meta = _load_history_meta(safe_stored_as)
    current_idx = meta.get("current_index", -1)
    steps = meta.get("steps", [])

    return {
        "filename": filename,
        "stored_as": safe_stored_as,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "target_column": target_col,
        "memory_usage_kb": round(df.memory_usage(deep=True).sum() / 1024, 2),
        "column_info": col_info,
        "preview_rows": preview_rows,
        "can_undo": current_idx > 0,
        "can_redo": 0 <= current_idx < len(steps) - 1,
        "history": [s["action"] for s in steps[:current_idx + 1]],
        "last_action": steps[current_idx]["action"] if 0 <= current_idx < len(steps) else None,
    }


# ── Small shared helpers ───────────────────────────────────

def _write_parquet_cache(task_id: str, X_train, X_test, y_train, y_test):
    """Save the processed matrices so later steps (EDA, training) don't recompute them."""
    cache_dir = os.path.join(UPLOAD_DIR, task_id)
    os.makedirs(cache_dir, exist_ok=True)
    X_train.to_parquet(os.path.join(cache_dir, "X_train.parquet"))
    X_test.to_parquet(os.path.join(cache_dir, "X_test.parquet"))
    pd.DataFrame(y_train).to_parquet(os.path.join(cache_dir, "y_train.parquet"))
    pd.DataFrame(y_test).to_parquet(os.path.join(cache_dir, "y_test.parquet"))


def _make_processed_preview(X_train, y_train, target_col_name: str) -> dict:
    """First 10 rows of the processed training data, shaped for the frontend table."""
    preview_df = X_train.head(10).copy()
    preview_df[target_col_name] = y_train.head(10).values
    for col in preview_df.select_dtypes(include=["float64", "float32"]).columns:
        preview_df[col] = preview_df[col].round(4)
    return {
        "columns": list(preview_df.columns),
        "rows": json.loads(preview_df.to_json(orient="records")),
        "total_rows": len(X_train),
        "total_cols": len(preview_df.columns),
    }


@app.post("/api/upload")
async def upload_csv(file: UploadFile=File(...)):
    if not file.filename.endswith(".csv"):
        raise HTTPException(status_code=400, detail="Only CSV files are allowed")
    
    file_id = str(uuid.uuid4())
    safe_name = f"{file_id}_{file.filename}"
    file_path = os.path.join(UPLOAD_DIR, safe_name)

    contents= await file.read()
    with open(file_path, "wb") as f:
        f.write(contents)

    try:
        df= _read_csv_safe(file_path)
    except Exception as e:
        os.remove(file_path)
        raise HTTPException(status_code=400, detail=f"Could not parse CSV: {str(e)}")
    
    if df.shape[1] < 2:
        os.remove(file_path)
        raise HTTPException(status_code=400, detail="CSV must have at least 2 columns (features + target).")
    
    _record_dataset_snapshot(safe_name, "Upload Dataset", df)
    return _build_dataset_response(df, safe_name, file.filename)



def _run_eda_task(task_id: str, file_path: str, stored_as: str):
    """Phase 1: Preprocessing & EDA"""
    log_lines = []

    def log(msg):
        log_lines.append(str(msg))

    def progress_cb(step_msg, pct):
        tasks[task_id]["step"] = step_msg
        tasks[task_id]["progress"] = pct

    try:
        # ── Step 1: Load CSV ──
        tasks[task_id]["status"] = "preprocessing"
        tasks[task_id]["step"] = "Loading dataset..."
        tasks[task_id]["progress"] = 5

        df = _read_csv_safe(file_path)
        original_filename = stored_as.split("_", 1)[1] if "_" in stored_as else stored_as
        log(f"========== PROCESSING: {original_filename} ==========")

        # ── Step 2: Preprocessing ──

        encoding_config = tasks[task_id].get("encoding_config", {})
        recipe_book = tasks[task_id].get("recipe_book", [])
        
        # Phase 1
        (X_train_cat, X_test_cat, X_train_cont, X_test_cont,
         y_train, y_test, categorical_cols, continuous_cols, target_col,
         original_shape, duplicates_removed, null_target_rows,
         columns_dropped_high_null, target_skewness, target_transform_applied, final_shape, index_cols_to_drop) = ml_pipeline.imp_phase1(df, log=log, progress_cb=progress_cb, recipe_book=recipe_book)
         
        # Phase 2
        X_train, X_test, y_train, y_test, preprocessing_report = ml_pipeline.imp_phase2(
            X_train_cat, X_test_cat, X_train_cont, X_test_cont,
            y_train, y_test, categorical_cols, continuous_cols, target_col,
            original_shape, duplicates_removed, null_target_rows,
            columns_dropped_high_null, target_skewness, target_transform_applied, final_shape,
            index_cols_to_drop=index_cols_to_drop, encoding_config=encoding_config, log=log, progress_cb=progress_cb
        )

        
        # ── Cache matrices to .parquet ──
        tasks[task_id]["step"] = "Caching intermediate data..."
        tasks[task_id]["progress"] = 25
        _write_parquet_cache(task_id, X_train, X_test, y_train, y_test)
        
        # ── Build processed dataset preview (first 10 rows) ──
        target_col = preprocessing_report.get("target_column", "target")
        processed_preview = _make_processed_preview(X_train, y_train, target_col)

        # Save preprocessing report to memory for the tournament phase
        tasks[task_id]["preprocessing_report"] = preprocessing_report
        
        # ── Add to Notebook History ──
        import pandas as pd
        X_all = pd.concat([X_train, X_test])
        y_all = pd.concat([y_train, y_test])
        df_processed = X_all.copy()
        df_processed[target_col] = y_all
        df_processed = df_processed.sort_index()

        safe_stored_as = os.path.basename(stored_as)
        meta = _load_history_meta(safe_stored_as)
        next_step_id = meta.get("current_index", -1) + 1

        code_str = f"""# ── Automated Preprocessing Pipeline ──
# Dropped nulls, handled missing values, encoded categoricals, and scaled features.
from pyodide.http import open_url
import pandas as pd
import io

# The preprocessed data was saved by the backend. We load it directly:
url = f"/api/notebook/{safe_stored_as}/snapshot/{next_step_id}"
csv_data = open_url(url).read()
df = pd.read_csv(io.StringIO(csv_data))
"""
        _record_dataset_snapshot(stored_as, "Automated Preprocessing Pipeline", df_processed, code=code_str, origin="pipeline")
        
        # ── Finish Phase 1 ──
        tasks[task_id]["results"] = {
            "task_id": task_id,
            "status": "eda_complete",
            "dataset_analysis": preprocessing_report,
            "processed_preview": processed_preview,
            "pipeline_log": "\n".join(log_lines),
        }
        tasks[task_id]["status"] = "eda_complete"
        tasks[task_id]["progress"] = 100
        tasks[task_id]["step"] = "EDA Complete"

    except Exception as e:
        tasks[task_id]["status"] = "error"
        tasks[task_id]["error"] = str(e)
        tasks[task_id]["step"] = "Error"
        tasks[task_id]["progress"] = 0
        log(f"\n❌ ERROR: {str(e)}")
        tasks[task_id]["results"] = {"pipeline_log": "\n".join(log_lines)}


# ── Run Pipeline Endpoint ──────────────────────────────────

@app.post("/api/prepare")
def prepare_data(body: dict):
    stored_as = body.get("stored_as")
    if not stored_as:
        raise HTTPException(status_code=400, detail="Missing 'stored_as' field.")
        
    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Uploaded file not found.")
        
    try:
        df = _read_csv_safe(file_path)
        
        # Run Phase 1
        (X_train_cat, X_test_cat, X_train_cont, X_test_cont,
         y_train, y_test, categorical_cols, continuous_cols, target_col,
         original_shape, duplicates_removed, null_target_rows,
         columns_dropped_high_null, target_skewness, target_transform_applied, final_shape, index_cols_to_drop) = ml_pipeline.imp_phase1(df)
         
        # Cache Phase 1 results so we don't have to run it again
        # Actually, if we just run it again in the background task, it's safer and less state to manage.
        # But wait! If we run it again, the random split is seeded (random_state=42) so it's deterministic.
        # So we can just fetch unique categories here and return them.
        
        cat_info = {}
        for col in categorical_cols:
            # Get up to 20 unique values for ordinal ordering
            unique_vals = X_train_cat[col].unique().tolist()
            if len(unique_vals) > 50:
                unique_vals = unique_vals[:50]
            cat_info[col] = unique_vals
            
        return {"categorical_cols": categorical_cols, "cat_info": cat_info}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/run")
async def run_pipeline(body: dict):
    """
    Launch the ML pipeline as a background task.
    """
    stored_as = body.get("stored_as")
    encoding_config = body.get("encoding_config", {})
    recipe_book = body.get("recipe_book", [])
    if not stored_as:
        raise HTTPException(status_code=400, detail="Missing 'stored_as' field.")

    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Uploaded file not found. Please re-upload.")

    task_id = str(uuid.uuid4())
    tasks[task_id] = {
        "status": "queued",
        "progress": 0,
        "step": "Queued",
        "results": None,
        "error": None,
        "start_time": time.time(),
        "encoding_config": encoding_config,
        "recipe_book": recipe_book,
        "stored_as": stored_as
    }

    import threading
    thread = threading.Thread(target=_run_eda_task, args=(task_id, file_path, stored_as), daemon=True)
    thread.start()

    return {"task_id": task_id}


@app.post("/api/train")
def run_train(body: dict):
    task_id = body.get("task_id")
    mode = body.get("mode", "standard")
    deleted_features = body.get("deleted_features", [])
    
    if not task_id or task_id not in tasks:
        raise HTTPException(status_code=404, detail="Task not found. Please re-upload dataset.")
        
    tasks[task_id]["status"] = "training"
    tasks[task_id]["step"] = "Starting Model Tournament..."
    tasks[task_id]["progress"] = 30
    
    import threading
    thread = threading.Thread(target=_run_train_task, args=(task_id, mode, deleted_features), daemon=True)
    thread.start()
    
    return {"task_id": task_id}


def _run_train_task(task_id: str, mode: str = "standard", deleted_features: list = None):
    """Phase 2: Model Tournament & Final Exam"""
    log_lines = []
    def log(msg):
        log_lines.append(str(msg))
        
    try:
        tasks[task_id]["step"] = "Loading cached data..."
        cache_dir = os.path.join(UPLOAD_DIR, task_id)
        
        import pandas as pd
        X_train = pd.read_parquet(os.path.join(cache_dir, "X_train.parquet"))
        X_test = pd.read_parquet(os.path.join(cache_dir, "X_test.parquet"))
        y_train = pd.read_parquet(os.path.join(cache_dir, "y_train.parquet")).iloc[:, 0]
        y_test = pd.read_parquet(os.path.join(cache_dir, "y_test.parquet")).iloc[:, 0]
        
        if deleted_features:
            cols_to_drop = [c for c in deleted_features if c in X_train.columns]
            if cols_to_drop:
                log(f"User manually excluded {len(cols_to_drop)} feature(s) before tournament: {', '.join(cols_to_drop)}")
                X_train = X_train.drop(columns=cols_to_drop)
                X_test = X_test.drop(columns=cols_to_drop)
                
                if X_train.shape[1] == 0:
                    raise ValueError("Cannot run tournament: All features were deleted!")

        # Remember which features the user excluded so a later single-model
        # re-evaluation (/api/model_details) uses the exact same feature set
        tasks[task_id]["excluded_features"] = deleted_features or []
        

        
        preprocessing_report = tasks[task_id].get("preprocessing_report", {})

        tasks[task_id]["progress"] = 30
        tasks[task_id]["status"] = "training"
        tasks[task_id]["step"] = "Training & evaluating 9 models..."

        # ── Step 3: Model Tournament ──
        def on_model_done(name, done, total):
            pct = 30 + int((done / total) * 45)  # 30% → 75%
            tasks[task_id]["progress"] = pct
            tasks[task_id]["step"] = f"Trained {done}/{total}: {name}"

        leaderboard, winning_model, recommendation_text, _ = ml_pipeline.ultimate_model_selector(
            X_train, y_train, log=log, on_model_done=on_model_done, mode=mode
        )

        tasks[task_id]["progress"] = 75
        tasks[task_id]["status"] = "evaluating"
        tasks[task_id]["step"] = "Final evaluation on held-out data..."

        winning_name = leaderboard.loc[0, "Model"]

        # ── Step 4: Final Exam ──
        _, final_metrics = ml_pipeline.final_exam(
            winning_name, winning_model, X_train, y_train, X_test, y_test, 
            target_transform_applied=preprocessing_report.get("target_transform_applied"), log=log
        )

        elapsed = round(time.time() - tasks[task_id]["start_time"], 2)
        log(f"\nPipeline completed successfully in {elapsed} seconds.")

        # ── Build leaderboard JSON ──
        leaderboard_list = []
        for idx, row in leaderboard.iterrows():
            leaderboard_list.append({
                "rank": idx + 1,
                "model": row["Model"],
                "cv_r2_mean": round(float(row["CV_R2_Mean"]), 4),
                "cv_r2_std": round(float(row["CV_R2_Std"]), 6),
            })

        # ── Assemble final results ──
        tasks[task_id]["results"] = {
            "task_id": task_id,
            "status": "complete",
            "dataset_analysis": preprocessing_report,
            "leaderboard": leaderboard_list,
            "best_model": {
                "name": winning_name,
                "cv_r2": leaderboard_list[0]["cv_r2_mean"],
                "final_r2": final_metrics["final_r2"],
                "final_rmse": final_metrics["final_rmse"],
                "recommendation": recommendation_text,
                "verdict": final_metrics["verdict"],
                "visuals": final_metrics.get("visuals", {})
            },
            "pipeline_log": "\n".join(log_lines),
            "execution_time_seconds": elapsed,
        }
        tasks[task_id]["status"] = "complete"
        tasks[task_id]["progress"] = 100
        tasks[task_id]["step"] = "Complete"

    except Exception as e:
        tasks[task_id]["status"] = "error"
        tasks[task_id]["error"] = str(e)
        tasks[task_id]["step"] = "Error"
        tasks[task_id]["progress"] = 0
        # Still save log for debugging
        log(f"\n❌ ERROR: {str(e)}")
        tasks[task_id]["results"] = {
            "pipeline_log": "\n".join(log_lines),
        }

# ── Column Management & Reversibility Endpoints ───────────

class ModelDetailsRequest(BaseModel):
    model: str

@app.post("/api/model_details/{task_id}")
def get_model_details(task_id: str, req: ModelDetailsRequest):
    """
    Retrains ONE requested model on the cached training matrices and returns
    the same payload shape as `best_model` (CV R², final R²/RMSE, verdict,
    recommendation and chart visuals). Lets the results page display any
    leaderboard model dynamically without re-running the whole tournament.
    Sync def on purpose: runs in FastAPI's thread pool so the event loop
    is not blocked while the model trains.
    """
    if task_id not in tasks:
        raise HTTPException(status_code=404, detail="Task not found.")
    task = tasks[task_id]
    model_name = (req.model or "").strip()

    registry = ml_pipeline.build_model_registry()
    if model_name not in registry:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown model '{model_name}'. Available: {', '.join(registry)}"
        )

    cache_dir = os.path.join(UPLOAD_DIR, task_id)
    x_path = os.path.join(cache_dir, "X_train.parquet")
    if not os.path.exists(x_path):
        raise HTTPException(status_code=404, detail="Cached dataset not found. Please re-run the pipeline.")

    # Per-model cache so toggling between leaderboard models is instant
    details_cache = task.setdefault("model_details_cache", {})
    if model_name in details_cache:
        return details_cache[model_name]

    try:
        X_train = pd.read_parquet(x_path)
        X_test = pd.read_parquet(os.path.join(cache_dir, "X_test.parquet"))
        y_train = pd.read_parquet(os.path.join(cache_dir, "y_train.parquet")).iloc[:, 0]
        y_test = pd.read_parquet(os.path.join(cache_dir, "y_test.parquet")).iloc[:, 0]

        # Keep the same feature set the tournament used (excluded features were dropped there)
        excluded = task.get("excluded_features") or []
        if excluded:
            cols_to_drop = [c for c in excluded if c in X_train.columns]
            if cols_to_drop:
                X_train = X_train.drop(columns=cols_to_drop)
                X_test = X_test.drop(columns=cols_to_drop)

        if X_train.shape[1] == 0:
            raise ValueError("No features available: every feature was excluded.")

        preprocessing_report = task.get("preprocessing_report") or {}

        _, final_metrics = ml_pipeline.final_exam(
            model_name,
            registry[model_name],
            X_train, y_train, X_test, y_test,
            target_transform_applied=preprocessing_report.get("target_transform_applied"),
            log=lambda msg: None,
        )

        # CV score straight from the stored leaderboard
        results_obj = task.get("results") or {}
        entry = next(
            (m for m in (results_obj.get("leaderboard") or []) if m.get("model") == model_name),
            None,
        )
        cv_r2 = entry.get("cv_r2_mean") if entry else None

        payload = {
            "name": model_name,
            "cv_r2": cv_r2,
            "final_r2": final_metrics["final_r2"],
            "final_rmse": final_metrics["final_rmse"],
            "recommendation": ml_pipeline.recommendation_text_for(model_name),
            "verdict": final_metrics["verdict"],
            "visuals": final_metrics.get("visuals", {}),
        }
        details_cache[model_name] = payload
        return payload

    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))


class UpdateDtypesRequest(BaseModel):
    stored_as: str
    dtypes: dict

@app.post("/api/update_dtypes")
async def update_dtypes(req: UpdateDtypesRequest):
    stored_as = os.path.basename(req.stored_as)
    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")
        
    try:
        df = _read_csv_safe(file_path)
        meta = _load_history_meta(stored_as)
        if not meta.get("steps"):
            _record_dataset_snapshot(stored_as, "Initial State", df)

        changes = []
        code_lines = []   # the same change, written as pandas code (for the notebook replay)
        for col, new_type in req.dtypes.items():
            if col in df.columns:
                old_dtype = str(df[col].dtype)
                if new_type == "numeric":
                    df[col] = pd.to_numeric(df[col], errors="coerce")
                    changes.append(f"{col} ({old_dtype} → numeric)")
                    code_lines.append(f'df[{col!r}] = pd.to_numeric(df[{col!r}], errors="coerce")')
                elif new_type == "string":
                    df[col] = df[col].astype(str)
                    changes.append(f"{col} ({old_dtype} → string)")
                    code_lines.append(f"df[{col!r}] = df[{col!r}].astype(str)")
                    
        df.to_csv(file_path, index=False)
        action_msg = f"Update dtype: {', '.join(changes) if changes else 'Type modified'}"
        _record_dataset_snapshot(stored_as, action_msg, df, code="\n".join(code_lines))
        
        return _build_dataset_response(df, stored_as)
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.post("/api/delete_column")
async def delete_column(body: dict):
    stored_as = os.path.basename(body.get("stored_as", ""))
    col_name = body.get("column_name")
    if not stored_as or not col_name:
        raise HTTPException(status_code=400, detail="Missing stored_as or column_name")
    
    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")
        
    df = _read_csv_safe(file_path)
    if col_name not in df.columns:
        raise HTTPException(status_code=400, detail="Column not found")
        
    if col_name == df.columns[-1]:
        raise HTTPException(status_code=400, detail="Cannot delete target column")
        
    if len(df.columns) <= 2:
        raise HTTPException(status_code=400, detail="Cannot delete last feature column")
        
    meta = _load_history_meta(stored_as)
    if not meta.get("steps"):
        _record_dataset_snapshot(stored_as, "Initial State", df)

    # Backup for legacy fallback
    backup_path = file_path + ".bak"
    shutil.copy2(file_path, backup_path)
    
    # Drop and save
    df = df.drop(columns=[col_name])
    df.to_csv(file_path, index=False)
    
    _record_dataset_snapshot(stored_as, f"Delete column '{col_name}'", df,
                             code=f"df = df.drop(columns=[{col_name!r}])")
    return _build_dataset_response(df, stored_as)

@app.post("/api/undo_dataset")
async def undo_dataset(body: dict):
    stored_as = os.path.basename(body.get("stored_as", ""))
    if not stored_as:
        raise HTTPException(status_code=400, detail="Missing stored_as")
        
    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")
        
    try:
        df, undone_action = _undo_dataset_snapshot(stored_as)
        resp = _build_dataset_response(df, stored_as)
        resp["undone_action"] = undone_action
        return resp
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Undo failed: {str(e)}")

@app.post("/api/redo_dataset")
async def redo_dataset(body: dict):
    stored_as = os.path.basename(body.get("stored_as", ""))
    if not stored_as:
        raise HTTPException(status_code=400, detail="Missing stored_as")
        
    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")
        
    try:
        df, redone_action = _redo_dataset_snapshot(stored_as)
        resp = _build_dataset_response(df, stored_as)
        resp["redone_action"] = redone_action
        return resp
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Redo failed: {str(e)}")

@app.post("/api/reset_dataset")
async def reset_dataset(body: dict):
    stored_as = os.path.basename(body.get("stored_as", ""))
    if not stored_as:
        raise HTTPException(status_code=400, detail="Missing stored_as")
        
    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")
        
    try:
        df, msg = _reset_dataset_snapshot(stored_as)
        resp = _build_dataset_response(df, stored_as)
        resp["reset_action"] = msg
        return resp
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.post("/api/dataset_history")
async def dataset_history(body: dict):
    stored_as = os.path.basename(body.get("stored_as", ""))
    if not stored_as:
        raise HTTPException(status_code=400, detail="Missing stored_as")
    meta = _load_history_meta(stored_as)
    current_idx = meta.get("current_index", -1)
    steps = meta.get("steps", [])
    return {
        "can_undo": current_idx > 0,
        "can_redo": 0 <= current_idx < len(steps) - 1,
        "current_index": current_idx,
        "steps": steps,
        "last_modified": meta.get("last_modified", 0)
    }


# ── Synchronization Endpoints ──────────────────────────────────
@app.get("/api/notebook/{stored_as}/sync")
async def notebook_sync(stored_as: str):
    """Return current dataset CSV and last_modified timestamp for sync."""
    safe_stored_as = os.path.basename(stored_as)
    file_path = os.path.join(UPLOAD_DIR, safe_stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")
    
    df = _read_csv_safe(file_path)
    meta = _load_history_meta(safe_stored_as)
    csv_data = df.to_csv(index=False)
    
    return {
        "csv": csv_data,
        "last_modified": meta.get("last_modified", 0),
        "rows": df.shape[0],
        "columns": df.shape[1],
        "columns_list": list(df.columns),
    }


@app.websocket("/ws/notebook/{stored_as}")
async def notebook_ws(websocket: WebSocket, stored_as: str):
    """WebSocket for real-time dataset synchronization."""
    await websocket.accept()
    safe_stored_as = os.path.basename(stored_as)
    file_path = os.path.join(UPLOAD_DIR, safe_stored_as)
    
    try:
        # Send initial state
        if os.path.exists(file_path):
            df = _read_csv_safe(file_path)
            meta = _load_history_meta(safe_stored_as)
            await websocket.send_json({
                "type": "init",
                "csv": df.to_csv(index=False),
                "last_modified": meta.get("last_modified", 0),
                "rows": df.shape[0],
                "columns": df.shape[1],
            })
        
        # Keep connection alive and wait for client to disconnect
        while True:
            # Wait for any message from client (keepalive)
            data = await websocket.receive_text()
            if data == "ping":
                await websocket.send_text("pong")
    except Exception:
        pass
    finally:
        await websocket.close()

def _execute_df_code(code_str: str, df: pd.DataFrame):
    """Executes Python code against DataFrame `df` and returns the output or result variable."""
    try:
        buffer = io.StringIO()
        local_scope = {"df": df, "pd": pd, "np": np}
        cleaned_code = code_str.strip()
        
        with redirect_stdout(buffer):
            exec(cleaned_code, globals(), local_scope)
            
        printed_out = buffer.getvalue().strip()
        var_result = local_scope.get("result")
        
        if var_result is not None:
            return str(var_result)
        elif printed_out:
            return printed_out
        else:
            return "Code executed successfully."
    except Exception as e:
        return f"Code Execution Error: {str(e)}"


# ── Chatbot Endpoint ───────────────────────────────────────
def _build_page_context(current_view, pipeline_results):
    """
    Describes the page the user is currently viewing and the numbers behind
    the charts visible on that page, so the chatbot can interpret references
    like 'this plot', 'the heatmap on this page', or 'the graph'.
    """
    if not current_view:
        return ""

    pr = pipeline_results or {}
    ds = pr.get("dataset_analysis") or {}
    eda = ds.get("eda_payload") or {}
    bm = pr.get("best_model") or {}
    visuals = bm.get("visuals") or {}
    lines = []

    if current_view == "v-upload":
        lines.append(
            "You are on the upload/landing page. The user is about to upload (or has just uploaded) "
            "a dataset; no pipeline results are visible here."
        )
    elif current_view == "v-preview":
        lines.append(
            "You are on the Dataset Preview page. It displays the raw uploaded table (first rows), "
            "all columns with their data types, and controls for changing data types, removing "
            "columns, undo/redo, and starting the pipeline."
        )
    elif current_view == "v-proc":
        lines.append(
            "You are on the processing page, where the ML pipeline (preprocessing + EDA) is running."
        )
    elif current_view == "v-eda":
        lines.append(
            "You are on the Data Insights (EDA) page. The charts currently visible are: "
            "(1) a Feature Importance bar chart (Mutual Information scores), "
            "(2) a Feature Skewness Before/After chart, "
            "(3) a Correlation Heatmap of the top features, and "
            "(4) a Feature Selection table showing each feature's mutual information and target "
            "correlation with Exclude/Restore controls. The Feature Forge panel (below the heatmap) "
            "lets the user create new features from formulas. "
            "The exact numbers behind all of these charts are provided in the EDA section below."
        )
    elif current_view == "v-results":
        lines.append(
            "You are on the Model Evaluation & Visual Diagnostics page. The charts currently visible are: "
            "(1) an Actual vs. Predicted scatter plot with the ideal y=x fit line, "
            "(2) a Residuals Distribution scatter plot with the zero-error line, "
            "(3) a Top Feature Importances horizontal bar chart, "
            "plus a Model Tournament Leaderboard table and a Champion Model card showing CV R², "
            "Final R², and RMSE."
        )
        pred = visuals.get("scatter_predicted") or []
        act = visuals.get("scatter_actual") or []
        res = visuals.get("scatter_residuals") or []
        try:
            if pred and act:
                lines.append(
                    f"Behind chart (1) — {min(len(pred), len(act))} test points; "
                    f"predicted range {min(pred):.2f} to {max(pred):.2f}, "
                    f"actual range {min(act):.2f} to {max(act):.2f}."
                )
            if res:
                mean_r = sum(res) / len(res)
                std_r = (sum((x - mean_r) ** 2 for x in res) / len(res)) ** 0.5
                lines.append(
                    f"Behind chart (2) — residuals: mean {mean_r:.4f}, std {std_r:.4f}, "
                    f"min {min(res):.4f}, max {max(res):.4f}."
                )
        except Exception:
            pass
        fi_labels = visuals.get("fi_labels") or []
        fi_vals = visuals.get("fi_values") or []
        if fi_labels and fi_vals:
            lines.append(
                "Behind chart (3) — top feature importance values: "
                + ", ".join(f"{k}={v:.4g}" for k, v in list(zip(fi_labels, fi_vals))[:12])
            )
        if bm:
            lines.append(
                f"Champion model card — {bm.get('name')}: CV R² {bm.get('cv_r2')}, "
                f"Final R² {bm.get('final_r2')}, RMSE {bm.get('final_rmse')}, "
                f"verdict: {bm.get('verdict')}."
            )
    else:
        return ""

    lines.append(
        "When the user refers to 'this page', 'the plot', 'the chart', 'the graph' or "
        "'the heatmap' without naming it explicitly, interpret it as the chart(s) listed above "
        "on this page and answer using the numbers provided here and in the sections below. "
        "You CAN see and reason about the current page's content, its charts, the dataset and "
        "the model results — do NOT claim that you cannot see plots or the screen."
    )
    return "\n\n### CURRENT PAGE CONTEXT (what the user is looking at right now):\n" + "\n".join(lines)


@app.post("/api/chat")
def chat_endpoint(body: dict):
    stored_as = body.get("stored_as")
    message = body.get("message", "")
    # Never hard-code secrets in source code. Set CHAT_API_KEY in your environment
    # (see the guide) or let the user type one into the chat settings.
    api_key = body.get("api_key", "").strip() or os.environ.get("CHAT_API_KEY", "")
    base_url = body.get("base_url", "").strip() or "http://localhost:20128/v1"
    model_name = body.get("model", "").strip() or "auto"
    chat_history = body.get("history", [])
    pipeline_results = body.get("results")
    current_view = body.get("current_view", "")

    # Optional screenshots of the charts currently visible on the user's page
    # (base64 data-URLs, max 4). Attached to the request so the model can SEE the plots.
    chart_images = body.get("chart_images") or []
    if isinstance(chart_images, str):
        chart_images = [chart_images]
    chart_images = [i for i in chart_images if isinstance(i, str) and i.startswith("data:image")][:4]
    
    if not stored_as:
        return {"response": "I cannot find the active dataset. Please upload a dataset first."}
        
    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        return {"response": "The dataset seems to be missing from the server."}
        
    try:
        df = _read_csv_safe(file_path)
        
        # Find the latest task for this dataset to get the recipe_book
        recipe_book = []
        encoding_config = {}
        for t_id, t_info in reversed(list(tasks.items())):
            if t_info.get("stored_as") == stored_as:
                recipe_book = t_info.get("recipe_book", [])
                encoding_config = t_info.get("encoding_config", {})
                if not pipeline_results and t_info.get("results"):
                    pipeline_results = t_info["results"]
                break
                
        # Apply the recipes to the dataframe so the chatbot sees the engineered features
        if recipe_book:
            import ml_pipeline
            df = ml_pipeline.apply_feature_forge(df, recipe_book)
            
        col_info = [f"- {c} ({df[c].dtype})" for c in df.columns]
        sample_data = df.head(3).to_csv(index=False)

        # Inject ML Pipeline & EDA Results if available
        results_context = ""
        if pipeline_results:
            context_parts = []
            
            # 1. Preprocessing & EDA Insights
            ds_analysis = pipeline_results.get("dataset_analysis", {})
            if ds_analysis:
                eda_parts = []
                orig_shape = ds_analysis.get('original_shape', [])
                fin_shape = ds_analysis.get('final_shape', [])
                if orig_shape and fin_shape:
                    eda_parts.append(f"- Original Shape: {orig_shape[0]} rows × {orig_shape[1]} cols, Processed Shape: {fin_shape[0]} rows × {fin_shape[1]} cols")
                
                target_col_name = ds_analysis.get('target_column', df.columns[-1])
                target_skew = ds_analysis.get('target_skewness')
                target_tf = ds_analysis.get('target_transform_applied')
                eda_parts.append(f"- Target Column: '{target_col_name}' (Target Skewness: {target_skew}, Transformation Applied: {target_tf})")
                
                dups = ds_analysis.get('duplicates_removed', 0)
                null_rows = ds_analysis.get('null_target_rows_dropped', 0)
                dropped_cols = ds_analysis.get('columns_dropped_high_null', [])
                eda_parts.append(f"- Cleaning Summary: {dups} duplicates removed, {null_rows} null-target rows dropped, Dropped high-null columns: {dropped_cols}")
                
                eda_payload = ds_analysis.get("eda_payload", {})
                if eda_payload:
                    # Feature Importance
                    importance = eda_payload.get("importance_scores", {})
                    if importance:
                        top_imp = list(importance.items())
                        imp_str = ", ".join([f"{k}: {v:.4f}" for k, v in top_imp])
                        eda_parts.append(f"- Feature Importance (Mutual Information Scores):\n  {imp_str}")
                    
                    # Skewness Tracker
                    skew_track = eda_payload.get("skewness_tracker", {})
                    if skew_track:
                        skew_str = ", ".join([f"{k} (before: {v['before']:.2f}, after: {v['after']:.2f})" for k, v in skew_track.items()])
                        eda_parts.append(f"- Skewness Transformations:\n  {skew_str}")
                    else:
                        eda_parts.append("- Skewness Transformations: No highly skewed features required transformation.")

                    # Correlation Matrix
                    corr_mat = eda_payload.get("correlation_matrix", {})
                    if corr_mat:
                        corr_pairs = []
                        cols_list = list(corr_mat.keys())
                        for i in range(len(cols_list)):
                            c1 = cols_list[i]
                            for j in range(i + 1, len(cols_list)):
                                c2 = cols_list[j]
                                val = corr_mat[c1].get(c2)
                                if val is not None:
                                    corr_pairs.append(f"{c1} vs {c2}: {val}")
                        if corr_pairs:
                            corr_str = "\n  ".join(corr_pairs)
                            eda_parts.append(f"- Feature Correlation Matrix (Pearson Correlation Coefficients):\n  {corr_str}")

                context_parts.append("### COMPREHENSIVE DATA EXPLORATION & PREPROCESSING (EDA):\n" + "\n".join(eda_parts))
            
            # 2. Tournament & Model Leaderboard
            best_model = pipeline_results.get("best_model")
            leaderboard = pipeline_results.get("leaderboard")
            if best_model or leaderboard:
                tourn_parts = []
                if best_model:
                    tourn_parts.append(f"- Winning Model: {best_model.get('name')}")
                    tourn_parts.append(f"- CV R² Score: {best_model.get('cv_r2')}, Final Test R²: {best_model.get('final_r2')}, Test RMSE: {best_model.get('final_rmse')}")
                    tourn_parts.append(f"- Model Evaluation Verdict: {best_model.get('verdict')}")
                    if best_model.get('recommendation'):
                        tourn_parts.append(f"- AI Recommendation: {best_model.get('recommendation')}")
                if leaderboard:
                    lb_str = "\n".join([f"  Rank {item.get('rank')}: {item.get('model')} (CV R²: {item.get('cv_r2_mean')} ± {item.get('cv_r2_std')})" for item in leaderboard])
                    tourn_parts.append(f"- Model Leaderboard:\n{lb_str}")
                context_parts.append("### MODEL TOURNAMENT & FINAL EXAM RESULTS:\n" + "\n".join(tourn_parts))
            
            if context_parts:
                results_context = "\n\n" + "\n\n".join(context_parts)

        # Inject the categorical encoding configuration so the model knows
        # which columns are already encoded (and how) in the pipeline.
        # Without this, the bot only sees the RAW string values in the CSV
        # and re-suggests encodings the user already applied.
        encoding_context = ""
        if encoding_config:
            enc_type_labels = {
                "onehot": "N-1 one-hot encoding (drop-first; the first category is the baseline)",
                "nominal": "one-hot encoding (drop-first; the first category is the baseline)",
                "ordinal": "ordinal encoding (categories mapped to numeric ranks in the listed order)",
                "target": "target encoding (each category replaced by the mean of the target)",
            }
            enc_lines = []
            for enc_col, enc_cfg in encoding_config.items():
                if not isinstance(enc_cfg, dict):
                    continue
                enc_type = enc_cfg.get("type", "onehot")
                label = enc_type_labels.get(enc_type, f"custom encoding ({enc_type})")
                order = enc_cfg.get("order")
                if enc_type == "ordinal" and order:
                    mapping = ", ".join(f"{v} = {i + 1}" for i, v in enumerate(order))
                    enc_lines.append(f"- '{enc_col}': {label} (mapping: {mapping})")
                else:
                    enc_lines.append(f"- '{enc_col}': {label}")
            if enc_lines:
                encoding_context = (
                    "\n\n### CATEGORICAL ENCODING ALREADY APPLIED BY THE PIPELINE:\n"
                    + "\n".join(enc_lines)
                    + "\nEvery EDA statistic, correlation, feature-importance value and model result shared above was computed AFTER these encodings were applied, so the raw string values shown in the sample above no longer exist in the analysis. Do NOT suggest applying, changing or re-encoding these columns. If the user asks about one, describe the encoding that was applied."
                )

        # What the user is looking at right now (page + visible charts + their numbers)
        page_context = _build_page_context(current_view, pipeline_results)

        system_prompt = f"""You are an expert Data Analyst AI with live code execution access to the full dataset in a pandas DataFrame named `df`.
Dataset info: {df.shape[0]:,} rows × {df.shape[1]} columns.
Target variable: '{df.columns[-1]}'.

Columns and data types:
{chr(10).join(col_info)}

3-row sample:
{sample_data}{page_context}{results_context}{encoding_context}

INSTRUCTIONS FOR DATA QUERIES:
If the user asks to find, count, filter, aggregate, or search specific row-level values in the dataset (e.g. "how many rows where Age is 21", "what is the mean salary of X", "show distribution of Y"), you MUST write a short executable Python code block wrapped in ```python ... ```.
Always assign the final numeric or text answer to a variable named `result` (e.g., `result = df[df['Age'] == 21].shape[0]`).
Never say you cannot access raw row-level data. You CAN query `df` directly!

DO NOT output any internal scratchpad outside your final markdown response."""

        if chart_images:
            system_prompt += (
                "\n\nSCREENSHOTS ATTACHED: The user's message includes screenshot image(s) of the "
                "chart(s) currently visible on their screen (the page context above says which page "
                "and which charts). You CAN now actually see the plots. Inspect the images carefully — "
                "read axis labels, point clouds, colors, legends and any visible artifacts — and "
                "describe or analyze exactly what is visible, cross-checked with the numeric context above."
            )

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        messages = [{"role": "system", "content": system_prompt}]
        messages.extend(chat_history)
        if not chat_history or chat_history[-1].get("role") != "user":
            if chart_images:
                # Multimodal user message: text + chart screenshots (OpenAI-compatible format)
                user_content = [{"type": "text", "text": message}]
                user_content.extend(
                    {"type": "image_url", "image_url": {"url": img}} for img in chart_images
                )
                messages.append({"role": "user", "content": user_content})
            else:
                messages.append({"role": "user", "content": message})

        payload = {
            "model": model_name,
            "messages": messages,
            "temperature": 0.1
        }

        chat_url = f"{base_url.rstrip('/')}/chat/completions"
        response = requests.post(chat_url, headers=headers, json=payload, timeout=120)

        if response.status_code != 200 and chart_images:
            # The model may not support vision — retry once as plain text
            text_messages = []
            for m in messages:
                c = m.get("content")
                if isinstance(c, list):
                    text_messages.append({
                        **m,
                        "content": " ".join(
                            p.get("text", "") for p in c
                            if isinstance(p, dict) and p.get("type") == "text"
                        ),
                    })
                else:
                    text_messages.append(m)
            payload["messages"] = text_messages
            response = requests.post(chat_url, headers=headers, json=payload, timeout=60)

        if response.status_code != 200:
            return {"response": f"Chat API Error ({response.status_code}): {response.text}"}
                
        completion = response.json()
        choices = completion.get("choices", [])
        if not choices:
            return {"response": "Received an empty response from the AI model service."}
            
        initial_reply = choices[0].get("message", {}).get("content", "") or choices[0].get("text", "")
        
        # Check if the AI generated Python code to run on `df`
        code_match = re.search(r"```python\s*(.*?)\s*```", initial_reply, re.DOTALL)
        if code_match:
            code_str = code_match.group(1)
            exec_res = _execute_df_code(code_str, df)
            
            # Step 2: Synthesis prompt with exact execution result
            synth_messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": message},
                {"role": "assistant", "content": initial_reply},
                {"role": "user", "content": f"The Python code was executed on DataFrame `df` and returned this exact result: {exec_res}\nNow provide the final clear natural language answer to the user based on this result. Do not output python code."}
            ]
            
            synth_payload = {
                "model": model_name,
                "messages": synth_messages,
                "temperature": 0.1
            }
            
            synth_resp = requests.post(chat_url, headers=headers, json=synth_payload, timeout=60)
            if synth_resp.status_code == 200:
                synth_choices = synth_resp.json().get("choices", [])
                if synth_choices:
                    final_ans = synth_choices[0].get("message", {}).get("content", "") or synth_choices[0].get("text", "")
                    return {"response": final_ans}
            
            # Fallback if synthesis call fails
            return {"response": f"Based on the dataset, **{exec_res}**."}

        return {"response": initial_reply}
        
    except Exception as e:
        return {"response": f"I encountered an error: {str(e)}"}


# ── Raw Dataset Endpoint for Pre-Pipeline Sandbox ───────────────────
@app.get("/api/raw_dataset/{stored_as}")
async def get_raw_dataset(stored_as: str):
    """Returns the raw uploaded CSV for sandbox before pipeline runs."""
    safe_stored_as = os.path.basename(stored_as)
    file_path = os.path.join(UPLOAD_DIR, safe_stored_as)
    
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Dataset not found.")
    
    return FileResponse(file_path, media_type="text/csv")


# ═══════════════════════════════════════════════════════════
#  PYTHON NOTEBOOK  (Python runs in the BROWSER, the server keeps the books)
# ═══════════════════════════════════════════════════════════
# Important design rule: the server NEVER executes notebook code.
# Notebook cells run inside the user's browser (Pyodide). The server only
#   1. tells the browser which earlier steps to replay      -> /state and /base
#   2. receives the resulting dataset when the user commits  -> /commit
#
# Every dataset change (UI button OR committed notebook cells) is one "step" in
# the history stored by _record_dataset_snapshot(), together with the code that
# produced it. Replaying the steps in order on the original upload rebuilds
# exactly the dataset you see in the app.

@app.get("/api/notebook/{stored_as}/state")
async def notebook_state(stored_as: str):
    """The ordered list of steps (with code) that lead to the current dataset."""
    stored_as = os.path.basename(stored_as)
    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Dataset not found.")

    meta = _load_history_meta(stored_as)
    steps = meta.get("steps", [])
    idx = meta.get("current_index", -1)

    if not steps or idx < 0:
        # Brand-new upload with no history yet: the file itself is the starting point.
        df = _read_csv_safe(file_path)
        return {
            "has_history": False,
            "replayable": True,
            "steps": [],
            "expected": {"columns": [str(c) for c in df.columns], "rows": int(len(df))},
        }

    active = steps[: idx + 1]          # steps after an undo are not part of the present
    # Step 0 is the original upload (no code needed). Every later step needs code to be replayable;
    # history written by older versions of this app has no code -> not replayable.
    replayable = all(st.get("code") is not None for st in active[1:])
    return {
        "has_history": True,
        "replayable": replayable,
        "steps": [
            {
                "step_id": st["step_id"],
                "action": st["action"],
                "origin": st.get("origin", "ui"),
                "code": st.get("code"),
                "cells": st.get("cells"),
            }
            for st in active
        ],
        "expected": {"columns": [str(c) for c in active[-1]["columns"]], "rows": active[-1]["rows"]},
    }


@app.get("/api/notebook/{stored_as}/base")
async def notebook_base(stored_as: str):
    """The ORIGINAL upload (history step 0): the starting point for replaying steps."""
    stored_as = os.path.basename(stored_as)
    steps = _load_history_meta(stored_as).get("steps", [])
    if steps:
        snap = os.path.join(_get_history_folder(stored_as), steps[0]["file"])
        if os.path.exists(snap):
            return FileResponse(snap, media_type="text/csv")
    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Dataset not found.")
    return FileResponse(file_path, media_type="text/csv")


def _rebuild_pipeline_cache(task_id: str, task: dict, df: pd.DataFrame, user_encoding: dict):
    """
    Re-run Phase 1 + Phase 2 on `df` (plus the task's Feature Forge recipes) and refresh
    the cached matrices, so the EDA page and the tournament see the committed data.

    Returns (needs_encoding_response, pipeline_payload). Exactly one of them is None.
    Raises ValueError for problems the user should read (bad target, recipe broken by the code...).
    """
    recipe_book = task.get("recipe_book") or None
    try:
        (X_train_cat, X_test_cat, X_train_cont, X_test_cont,
         y_train, y_test, categorical_cols, continuous_cols, target_col,
         original_shape, duplicates_removed, null_target_rows,
         columns_dropped_high_null, target_skewness, target_transform_applied,
         final_shape, index_cols_to_drop) = ml_pipeline.imp_phase1(df.copy(), recipe_book=recipe_book)
    except ValueError as e:
        if recipe_book and ("Formula" in str(e) or "Recipe" in str(e)):
            raise ValueError(
                f"{e}  (Your notebook code probably removed or renamed a column that a "
                f"Feature Forge recipe needs.)"
            )
        raise

    # Keep earlier encoding choices, but only for columns that are still categorical.
    merged = {**task.get("encoding_config", {}), **(user_encoding or {})}
    reconciled = {k: v for k, v in merged.items() if k in set(categorical_cols)}

    unmapped = [c for c in categorical_cols if c not in reconciled]
    if unmapped:
        cat_info = {c: X_train_cat[c].unique().tolist()[:50] for c in unmapped}
        return ({
            "status": "needs_encoding",
            "message": "Your code created new categorical columns. Choose how to encode them.",
            "unmapped_columns": unmapped,
            "cat_info": cat_info,
            "temporary_state": reconciled,
        }, None)

    X_train_final, X_test_final, y_train, y_test, report = ml_pipeline.imp_phase2(
        X_train_cat, X_test_cat, X_train_cont, X_test_cont,
        y_train, y_test, categorical_cols, continuous_cols, target_col,
        original_shape, duplicates_removed, null_target_rows,
        columns_dropped_high_null, target_skewness, target_transform_applied, final_shape,
        index_cols_to_drop=index_cols_to_drop, encoding_config=reconciled,
    )
    _write_parquet_cache(task_id, X_train_final, X_test_final, y_train, y_test)

    preview = _make_processed_preview(X_train_final, y_train, report.get("target_column", "target"))
    task["preprocessing_report"] = report
    task["encoding_config"] = reconciled
    if task.get("results"):
        task["results"]["dataset_analysis"] = report
        task["results"]["processed_preview"] = preview
        task["results"]["eda_payload"] = report.get("eda_payload", {})

    return None, {
        "dataset_analysis": report,
        "processed_preview": preview,
        "eda_payload": report.get("eda_payload", {}),
    }


class NotebookCommitRequest(BaseModel):
    csv_data: str                    # the dataset AFTER the cells ran (df.to_csv)
    cells: List[str]                 # the committed cells' code, top to bottom
    encoding_config: dict = {}       # only sent after the encoding dialog
    task_id: Optional[str] = None    # set when the pipeline has already run


@app.post("/api/notebook/{stored_as}/commit")
async def notebook_commit(stored_as: str, req: NotebookCommitRequest):
    """
    Make the notebook's result the dataset of the whole app:
      * the dataset file is replaced and a new history step (with the code) is recorded,
      * if the pipeline already ran, Phase 1/2 + EDA are recomputed from the new data.
    Nothing is written unless every check passes.
    """
    stored_as = os.path.basename(stored_as)
    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Dataset not found.")

    cells = [c for c in req.cells if c.strip()]
    if not cells:
        raise HTTPException(status_code=400, detail="Nothing to commit - the cells are empty.")

    current_df = _read_csv_safe(file_path)
    target_col = current_df.columns[-1]       # this app treats the LAST column as the target

    try:
        new_df = pd.read_csv(io.StringIO(req.csv_data))
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Could not read the notebook's dataset: {e}")



    if len(new_df) == 0:
        raise HTTPException(status_code=400, detail="The dataset has no rows left after your code.")
    if target_col not in new_df.columns:
        raise HTTPException(
            status_code=400,
            detail=f"The target column '{target_col}' no longer exists in df. Keep it (the app predicts it).",
        )

    warnings = []
    step_code = "\n\n".join(cells)
    if new_df.columns[-1] != target_col:
        # `df["new"] = ...` appends the new column LAST, which would silently make it the target.
        new_df = new_df[[c for c in new_df.columns if c != target_col] + [target_col]]
        warnings.append(f"Target column '{target_col}' was moved back to the last position.")
        # Write the fix into the stored code too, so replaying the history gives the SAME dataset.
        step_code += (
            "\n\n# (added by the app) keep the target column last\n"
            f"df = df[[c for c in df.columns if c != {target_col!r}] + [{target_col!r}]]"
        )
    if new_df.shape[1] < 2:
        raise HTTPException(status_code=400, detail="The dataset needs at least 2 columns (features + target).")

    # If the pipeline already ran for this dataset, rebuild its cache first.
    # (Nothing has been saved yet, so any error leaves the project untouched.)
    task = tasks.get(req.task_id) if req.task_id else None
    if task is not None and task.get("stored_as") != stored_as:
        task = None
    pipeline_payload = None
    if task is not None:
        try:
            needs_encoding, pipeline_payload = _rebuild_pipeline_cache(
                req.task_id, task, new_df, req.encoding_config
            )
        except ValueError as e:
            raise HTTPException(status_code=400, detail=str(e))
        if needs_encoding:
            return needs_encoding

    # All good -> persist: dataset file + a history step that carries the code.
    if not _load_history_meta(stored_as).get("steps"):
        _record_dataset_snapshot(stored_as, "Initial State", current_df)
    new_df.to_csv(file_path, index=False)
    n = len(cells)
    _record_dataset_snapshot(
        stored_as,
        f"Notebook commit ({n} cell{'s' if n != 1 else ''})",
        new_df,
        code=step_code,
        origin="notebook",
        cells=cells,
    )

    return {
        "status": "success",
        "dataset": _build_dataset_response(new_df, stored_as),
        "pipeline": pipeline_payload,
        "warnings": warnings,
    }


# ── Status Endpoint ────────────────────────────────────────
@app.get("/api/status/{task_id}")
async def get_status(task_id: str):
    if task_id not in tasks:
        raise HTTPException(status_code=404, detail="Task not found.")
    task = tasks[task_id]
    return {
        "task_id": task_id,
        "status": task["status"],
        "progress": task["progress"],
        "step": task["step"],
        "error": task["error"],
    }


# ── Results Endpoint ───────────────────────────────────────
@app.get("/api/results/{task_id}")
async def get_results(task_id: str):
    if task_id not in tasks:
        raise HTTPException(status_code=404, detail="Task not found.")
    task = tasks[task_id]
    if task["status"] == "error":
        return JSONResponse(
            status_code=422,
            content={
                "status": "error",
                "error": task["error"],
                "pipeline_log": task["results"].get("pipeline_log", "") if task["results"] else "",
            }
        )
    if task["status"] not in ("complete", "eda_complete"):
        raise HTTPException(status_code=202, detail="Pipeline still running.")
    return task["results"]


# ── Feature Forge Update Endpoint ───────────
class FeatureForgeRequest(BaseModel):
    recipe_book: list
    encoding_config: dict = {}

@app.post("/api/feature_forge/{task_id}")
async def feature_forge_update(task_id: str, req: FeatureForgeRequest):
    """
    Intercepts Feature Forge updates from the EDA page.
    Runs Phase 1 with the recipe, reconciles encoding config,
    halts if new categoricals are found, silently finishes if all clear.
    """
    if task_id not in tasks:
        raise HTTPException(status_code=404, detail="Task not found.")

    task = tasks[task_id]
    stored_as = task.get("stored_as")
    if not stored_as:
        raise HTTPException(status_code=400, detail="No stored file reference found for this task.")

    file_path = os.path.join(UPLOAD_DIR, stored_as)
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Original uploaded file not found.")

    try:
        # Load the RAW CSV (not cached parquet — we need original data)
        raw_df = _read_csv_safe(file_path)

        # ═══════════════════════════════════════
        # 1. RUN PHASE 1 (Process the Math & Drop Old Columns)
        # ═══════════════════════════════════════
        (X_train_cat, X_test_cat, X_train_cont, X_test_cont,
         y_train, y_test, categorical_cols, continuous_cols, target_col,
         original_shape, duplicates_removed, null_target_rows,
         columns_dropped_high_null, target_skewness, target_transform_applied,
         final_shape, index_cols_to_drop) = ml_pipeline.imp_phase1(
            raw_df, recipe_book=req.recipe_book
        )

        # ═══════════════════════════════════════
        # 2. THE DELTA CHECK (Reconcile the State)
        # ═══════════════════════════════════════

        # Step A: Ghost Purge — delete config entries for columns dropped by the formula
        active_cat_set = set(categorical_cols)
        reconciled_config = {k: v for k, v in req.encoding_config.items() if k in active_cat_set}

        # Step B: Halt Trigger — find new categorical features with no config
        unmapped_new_columns = [col for col in categorical_cols if col not in reconciled_config]

        if unmapped_new_columns:
            # Build cat_info for the unmapped columns so the encoding modal can render
            cat_info = {}
            for col in unmapped_new_columns:
                unique_vals = X_train_cat[col].unique().tolist()
                if len(unique_vals) > 50:
                    unique_vals = unique_vals[:50]
                cat_info[col] = unique_vals

            return {
                "status": "needs_encoding",
                "message": "New categorical features detected from the formula.",
                "unmapped_columns": unmapped_new_columns,
                "cat_info": cat_info,
                "temporary_state": reconciled_config
            }

        # ═══════════════════════════════════════
        # 3. SILENT FINISH (No new categoricals — run Phase 2)
        # ═══════════════════════════════════════
        X_train_final, X_test_final, y_train, y_test, preprocessing_report = ml_pipeline.imp_phase2(
            X_train_cat, X_test_cat, X_train_cont, X_test_cont,
            y_train, y_test, categorical_cols, continuous_cols, target_col,
            original_shape, duplicates_removed, null_target_rows,
            columns_dropped_high_null, target_skewness, target_transform_applied, final_shape,
            index_cols_to_drop=index_cols_to_drop,
            encoding_config=reconciled_config
        )

        # Re-cache the updated parquet files
        _write_parquet_cache(task_id, X_train_final, X_test_final, y_train, y_test)

        # Update the task's preprocessing report & encoding config
        task["preprocessing_report"] = preprocessing_report
        task["encoding_config"] = reconciled_config
        task["recipe_book"] = req.recipe_book

        # Build processed preview
        target_col_name = preprocessing_report.get("target_column", "target")
        processed_preview = _make_processed_preview(X_train_final, y_train, target_col_name)

        # Update task results so the train endpoint picks up the new data
        if "results" in task and task["results"]:
            task["results"]["dataset_analysis"] = preprocessing_report
            task["results"]["processed_preview"] = processed_preview

        return {
            "status": "success",
            "eda_payload": preprocessing_report.get("eda_payload", {}),
            "processed_preview": processed_preview,
            "dataset_analysis": preprocessing_report
        }

    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))


# ── EDA Recalculation Endpoint ───────────
class RecalculateEDARequest(BaseModel):
    deleted_features: List[str]

@app.post("/api/recalculate_eda/{task_id}")
async def recalculate_eda(task_id: str, req: RecalculateEDARequest):
    """
    Recomputes the EDA payload (feature importance, correlation matrix,
    skewness tracker) from the CACHED training matrix with the user's
    excluded features removed. Fast — no re-preprocessing.
    Recipe changes are handled by /api/feature_forge instead, which
    re-runs Phase 1 + Phase 2 from the raw CSV and re-caches the parquet.
    """
    if task_id not in tasks:
        raise HTTPException(status_code=404, detail="Task not found.")

    task = tasks[task_id]
    cache_dir = os.path.join(UPLOAD_DIR, task_id)
    X_train_path = os.path.join(cache_dir, "X_train.parquet")
    if not os.path.exists(X_train_path):
        raise HTTPException(status_code=404, detail="Cached dataset not found. Please re-run the pipeline.")

    try:
        X_train = pd.read_parquet(X_train_path)
        y_train = pd.read_parquet(os.path.join(cache_dir, "y_train.parquet")).iloc[:, 0]

        cols_to_drop = [c for c in req.deleted_features if c in X_train.columns]
        if cols_to_drop:
            X_train = X_train.drop(columns=cols_to_drop)

        if X_train.shape[1] == 0:
            raise ValueError("Cannot recalculate EDA: every feature is excluded.")

        target_col = task.get("preprocessing_report", {}).get("target_column", "target")

        old_eda = task.get("results", {}).get("dataset_analysis", {}).get("eda_payload", {})
        # Keep only skewness entries for columns that still exist
        skewness_tracker = {
            k: v for k, v in old_eda.get("skewness_tracker", {}).items()
            if k in X_train.columns
        }

        new_eda_payload = ml_pipeline.calculate_eda(
            X_train, y_train, target_col, skewness_tracker=skewness_tracker
        )

        if "results" in task and "dataset_analysis" in task["results"]:
            task["results"]["dataset_analysis"]["eda_payload"] = new_eda_payload

        return new_eda_payload

    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/api/notebook/{stored_as}/snapshot/{step_id}")
async def get_notebook_snapshot(stored_as: str, step_id: int):
    safe_stored_as = os.path.basename(stored_as)
    folder = _get_history_folder(safe_stored_as)
    snap_path = os.path.join(folder, f"snap_{step_id}.csv")
    if os.path.exists(snap_path):
        from fastapi.responses import FileResponse
        return FileResponse(snap_path, media_type="text/csv")
    raise HTTPException(status_code=404, detail="Snapshot not found")

@app.get("/{full_path:path}", response_class=HTMLResponse)
async def serve_react_app(full_path: str):
    # Prevent catching API requests that were not found
    if full_path.startswith("api/"):
        raise HTTPException(status_code=404, detail="API endpoint not found")

    index_path = os.path.join(REACT_BUILD_DIR, "index.html")
    if not os.path.exists(index_path):
        raise HTTPException(
            status_code=404, 
            detail=f"React build index.html not found at {index_path}. Run 'npm run build' in frontend directory."
        )
    return FileResponse(index_path)

        
    